// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommanderConn(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommanderConn'](arg1, arg2, arg3);
}

export function CommanderDisconn(arg1) {
  return window['go']['main']['App']['CommanderDisconn'](arg1);
}

export function CommanderIsLogging(arg1) {
  return window['go']['main']['App']['CommanderIsLogging'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogFolderOpen(arg1) {
  return window['go']['main']['App']['LogFolderOpen'](arg1);
}

export function LogPrint(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogPrint'](arg1, arg2, arg3);
}

export function SendData(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendData'](arg1, arg2, arg3);
}

export function SerialList() {
  return window['go']['main']['App']['SerialList']();
}

export function SetPage(arg1) {
  return window['go']['main']['App']['SetPage'](arg1);
}
