// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommanderConn(arg1:number,arg2:string,arg3:string):Promise<boolean>;

export function DisConn(arg1:Array<string>):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function LogPrint(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SerialList():Promise<Array<string>>;

export function SetPage(arg1:string):Promise<void>;
